GET http://localhost:5227/games/

###
GET http://localhost:5227/games/1

###
POST http://localhost:5227/games
Content-Type: application/json

{
  "Name": "super mario",
  "Genre": "Platformer",
  "Price": 59.99,
  "ReleaseDate": "2023-02-15"
}

###
PUT http://localhost:5227/games/1
Content-Type: application/json

{
  "Name": "super mario",
  "Genre": "Platformer",
  "Price": 59.99,
  "ReleaseDate": "2023-02-15"
}

###
DELETE http://localhost:5227/games/2
